# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WDMCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WDMCityMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_x', models.IntegerField(default=0)),
                ('city_y', models.IntegerField(default=0)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.WDMCity')),
            ],
        ),
        migrations.CreateModel(
            name='WDMCityMapItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WDMCityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WDMWorldMapItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('image_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='wdmcitymap',
            name='cmit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.WDMCityMapItemType'),
        ),
        migrations.AddField(
            model_name='wdmcity',
            name='city_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.WDMCityType'),
        ),
    ]
